_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 41
                - 55
                - 80
            "2":
                - 1
                - 41
                - 55
                - 80
            "3":
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.8.20
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
batch_size:
    value: 1
epochs:
    value: 50
lr:
    value: 0.01
