DATASET:
    base_path: '/home/choi/hwang/workspace/HeadHunter/datasets/train'
    train: '/home/choi/hwang/workspace/HeadHunter/datasets/train/1_scut_head.txt'
    valid: '/home/choi/hwang/workspace/HeadHunter/datasets/valid/1_scut_head.txt'

    benchmark: 'Combined'
    mean_std: [[117, 110, 105], [67.10, 65.45, 66.23]]
    max_size: 1000
    min_size: 600


TRAINING:
    exp_name: 'SCUT_up_F_anchor_v3'
    backbone : 'resnet50'
    only_backbone : False
    pretrained_model: ''
    save_dir: '/home/choi/hwang/workspace/HeadHunter/output_weights'
    start_epoch: 1
    eval_every: 1
    log_dir: './Logs/'
    milestones: [5,10,15]
    max_epoch: 20

HYPER_PARAM:
    learning_rate: 0.01
    momentum: 0.9
    weight_decay: 0.0005
    gamma: 0.5
    batch_size: 1

NETWORK:
    use_deform: False
    ohem: True
    context: 'cpm'
    custom_sampling: False
    soft_nms: False
    upscale_rpn: False
    median_anchors: True
    # comb_anchors = (
    #     (12, 32, 64, 112, 196, 256, 384, 512),
    #     (12, 32, 64, 112, 196, 256, 384, 512),
    #     (12, 32, 64, 112, 196, 256, 384, 512),
    #     (12, 32, 64, 112, 196, 256, 384, 512),
    # )
